### ISSUE TITLE
Can you help ?

### ISSUE THREAD

**Issue by Azrael1980** [jmanuelng/MEM_EnableWOL#1]
![изображение](https://github.com/jmanuelng/MEM_EnableWOL/assets/29340110/4213ace1-7874-4104-8787-c71d6545af6b)

PS C:\install> .\Detect_WOL.ps1
>> 

Checking Manufacturer
Manufacturer is HP. Installing module and trying to get WOL State.
Installing HP Provider if needed.
Install-Package : Не удается найти параметр, соответствующий имени параметра "AcceptLicense".
C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 знак:68
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                                                        ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Package], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 
Import-Module : Указанный модуль "HPCMSL" не был загружен, так как ни в одном из каталогов модулей не был обнаружен действительный файл модуля.
C:\install\Detect_WOL.ps1:129 знак:13
+             Import-Module -Global HPCMSL
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (HPCMSL:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand
 
an error occured. Could not find WOL state
ВЁ-1 : Имя "ВЁ-1" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьте правильность написания имени, а также наличие и правильность пути, после чего повторите  
попытку.
C:\install\Detect_WOL.ps1:141 знак:27
+                 $result = ВЁ-1
+                           ~~~~
    + CategoryInfo          : ObjectNotFound: (ВЁ-1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
BIOS WoL status:
OS WoL status: Healthy - All NICs enabled for WOL within the OS.
OK 01/29/2024 09:31:50 : HP system. Installed HP BIOS provider. Error getting HP WoL setting. NICs with WoL enabled in OS. OS WoL value: Healthy - All NICs enabled for WOL within the OS.

**Comment by jmanuelng** [comment]
Hola!

Seems like the script failed trying to install module HPCMSL.

Make sure:
- You're running PowerShell 5.1 or higher.
- You have Administrative priviliges on the Device
- If behinde proxy or firewall, make sure it allows the required Internet connectivity to discover and donwload content from PSGallery.
  - *.powershellgallery.com
  - onegetcdn.azureedge.net
  - psg-prod-centralus.azureedge.net
  - psg-prod-eastus.azureedge.net
  - devopsgallerystorage.blob.core.windows.net
  - go.microsoft.com

I also checked and the HPCMSL module is still availabe in PS Gallery: 
https://www.powershellgallery.com/packages/HPCMSL/1.6.5

Maybe try manually installing the module on a test device, if ir error, try to fix module installation and try the script again.

`Install-Module -Name HPCMSL -RequiredVersion 1.6.5`

As per Powershell Gallery, 1.6.5 is the "current version"

`Install-Module -Name "HPCMSL" `

This will install latest version


Do let me know if you find a fix to update script accordingly.
